copy all changes from book version
ritza-co/replit.github.io pull request #2
Opened 2020-09-22 07:53 UTC by eugenedorfling

Copied all the book updates over to this version to compare and update what needs to be updated.

2020-09-25 12:55 UTC, eugenedorfling commented on tutorials/00-overview.md
> +In a series of tutorials, you'll go from beginner to expert in coding with Repl.it. While these lessons are designed to be taken in order, they each make sense on their own too, so feel free to jump
```suggestion
In a series of 12 tutorials, you'll go from beginner to expert in coding with Repl.it. While these lessons are designed to be taken in order, they each make sense on their own too, so feel free to jump in wherever looks the most interesting to you.
```

2020-09-25 12:57 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 1: Introduction to Repl.it and using the IDE
```suggestion
#### [Lesson 1: Introduction to Repl.it and using the IDE](./01-introduction-to-the-repl-it-ide)
```

2020-09-25 12:58 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 2: Working with files using Repl.it
```suggestion
#### [Lesson 2: Working with files using Repl.it](./02-managing-files-using-repl-it)
```

2020-09-25 12:58 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 3: Managing dependencies with Repl.it
```suggestion
#### [Lesson 3: Managing dependencies with Repl.it](./03-handling-dependencies-with-repl-it)
```

2020-09-25 12:59 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 4: Data science: plotting and graphing
```suggestion
#### [Lesson 4: Data science: plotting and graphing](./04-data-science-and-visualisation-with-repl-it)
```

2020-09-25 12:59 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 5: Pair programming and using multiplayer
```suggestion
#### [Lesson 5: Pair programming and using multiplayer](./05-pair-programming-using-multiplayer-with-repl-it)
```

2020-09-25 13:00 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 6: Running projects from GitHub
```suggestion
#### [Lesson 6: Running projects from GitHub](./06-github-and-run-button)
```

2020-09-25 13:00 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 7: Building a game with PyGame
```suggestion
#### [Lesson 7: Building a game with PyGame](./07-building-a-game-with-pygame)
```

2020-09-25 13:00 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 8: Can you keep a secret? What about from time travellers?
```suggestion
#### [Lesson 8: Can you keep a secret? What about from time travellers?](./08-storing-secrets-and-history)
```

2020-09-25 13:01 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 9: Introduction to TDD using PyTest
```suggestion
#### [Lesson 9: Building a web application with TDD](./09-test-driven-development)
```

2020-09-25 13:02 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 10: Become an elite hacker with productivity hacks
```suggestion
#### [Lesson 10: Become an elite hacker with productivity hacks](./10-productivity-hacks)
```

2020-09-25 13:04 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Beginner web scraping with Python and Repl.it
```suggestion
#### [Beginner web scraping with Python and Repl.it](https://ritza.co/showcase/repl.it/beginner-web-scraping-with-python-and-repl-it)
```

2020-09-25 13:04 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Building news word clouds using Python and Repl.it
```suggestion
#### [Building news word clouds using Python and Repl.it](https://ritza.co/showcase/repl.it/building-news-word-clouds-using-python-and-repl-it)
```

2020-09-25 13:04 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Building a Discord Bot with Python and Repl.it
```suggestion
#### [Building a Discord Bot with Python and Repl.it](https://ritza.co/showcase/repl.it/building-a-discord-bot-with-python-and-repl-it)
```

2020-09-25 13:05 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Building a Discord bot with Node.js and Repl.it
```suggestion
#### [Building a Discord bot with Node.js and Repl.it](https://ritza.co/showcase/repl.it/building-a-discord-bot-with-node-and-repl-it)
```

2020-09-25 13:05 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Creating and hosting a basic web application with Django and Repl.it
```suggestion
#### [Creating and hosting a basic web application with Django and Repl.it](https://ritza.co/showcase/repl.it/creating-and-hosting-a-basic-django-application-with-django-and-repl-it)
```

2020-09-25 13:06 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Building a CRM app with NodeJS, Repl.it, and MongoDB
```suggestion
#### [Building a CRM app with NodeJS, Repl.it, and MongoDB](https://ritza.co/showcase/repl.it/building-a-crm-app-with-nodejs-repl-it-and-mongo-db)
```

2020-09-25 13:06 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Introduction to Machine Learning with Python and repl.it
```suggestion
#### [Introduction to Machine Learning with Python and repl.it](https://ritza.co/showcase/repl.it/introduction-to-machine-learning-with-python-and-repl-it)
```

2020-09-25 13:06 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Quicksort tutorial: Python implementation with line by line explanation
```suggestion
#### [Quicksort tutorial: Python implementation with line by line explanation](https://ritza.co/showcase/repl.it/quicksort-tutorial-python-implementation-with-line-by-line-explanation)
```

2020-09-25 13:07 UTC, eugenedorfling commented on tutorials/00-overview.md
> +By this stage you'll have made a few mistakes. Learn the TDD way and how to write code that tests your other code to catch frustrating errors before they can hurt anyone. Repetitive jobs is what comp
Not sure which is the latest? or which is preferred?

2020-09-25 13:12 UTC, eugenedorfling commented on tutorials/03-handling-dependencies-with-repl-it.md
> +
```suggestion

```

2020-09-25 13:12 UTC, eugenedorfling commented on tutorials/03-handling-dependencies-with-repl-it.md
> +
```suggestion
```

2020-09-25 13:12 UTC, eugenedorfling commented on tutorials/03-handling-dependencies-with-repl-it.md
> +
```suggestion
```

2020-09-25 13:15 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> +![**Image 5:** *The ball falling at a constant rate.*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-05-falling-ball.png)
```suggestion
![**Image 5:** *The ball falling at a constant rate.*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-05-GIF-falling-ball.gif)
```

2020-09-25 13:16 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> +[*click to open gif*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-05-GIF-falling-ball.gif)
```suggestion
![**Image 5:** *The ball falling at a constant rate.*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-05-GIF-falling-ball.gif)
```

2020-09-25 13:19 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> -                    ball.speed = [0,-1]
Double-check the code here. Check if in sequence the ` ball.speed = [0, -1]` should be there and the below two lines removed rather?

2020-09-25 13:20 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> +[*click to open gif*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-06-GIF-bounce-off-roof.gif)
```suggestion
![**Image 6:** *Now we can bounce the ball off the ceiling.*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-06-GIF-bounce-off-roof.gif)
```

2020-09-25 13:21 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> +[*click to open gif*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-07-GIF-three-balls.gif)
```suggestion
![**Image 7:** *Juggling three balls.*](https://i.ritzastatic.com/repl/codewithrepl/07-pygame/07-07-GIF-three-balls.gif)
```

2020-09-25 13:22 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +*The images in this chapter are mostly .gif files, click* [*here*](https://docs.repl.it/tutorials/10-productivity-hacks) *to access the web version of this chapter*
```suggestion
```

2020-09-25 13:23 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +
```suggestion
```

2020-09-25 13:28 UTC, eugenedorfling commented on tutorials/12-audio.md
> +If you're stuck for ideas, continue on to Part 3 where we'll walk you through eight practical projects, focusing more on coding concepts than Repl.it features.
```suggestion
```

2020-09-25 13:29 UTC, eugenedorfling commented on tutorials/12-audio.md
> +If you're stuck for ideas, continue on to Part 3 where we'll walk you through eight practical projects, focusing more on coding concepts than Repl.it features.
```suggestion
```

2020-09-25 13:33 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 11: Keeping your data in check with the Repl.it database
```suggestion
#### [Lesson 11: Keeping your data in check with the Repl.it database] (./11-using-the-replit-database)
```

2020-09-25 13:34 UTC, eugenedorfling commented on tutorials/00-overview.md
> +#### Tutorial 12: Repl audio - control (or create) your music with code
```suggestion
#### [Lesson 12: Repl audio - control (or create) your music with code](./12-audio)
```

2020-09-25 13:40 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 2:** *Opening a file with the global command palette.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-02-find.png)
```suggestion
![**Image 2:** *Opening a file with the global command palette.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-02-GIF-find.gif)
```

2020-09-25 13:40 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 4:** *Copying the current selected line.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-04-duplicate-line-entries.png)
```suggestion
![**Image 4:** *Copying the current selected line.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-04-GIF-duplicate-line-entries.gif)
```

2020-09-25 13:41 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 5:** *Deleting selected lines of code.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-05-deleting-entire-lines.png)
```suggestion
![**Image 5:** *Deleting selected lines of code.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-05-GIF-deleting-entire-lines.gif)
```

2020-09-25 13:42 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 6:** *Inserting lines.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-06-insert-blank-lines.png)
```suggestion
![**Image 6:** *Inserting lines.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-06-GIF-insert-blank-lines.gif)
```

2020-09-25 13:42 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 7:** *Indenting a line.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-07-indenting-lines.png)
```suggestion
![**Image 7:** *Indenting a line.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-07-GIF-indenting-lines.gif)
```

2020-09-25 13:42 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 8:** *Moving the current line selection.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-08-moving-blocks-code.png)
```suggestion
![**Image 8:** *Moving the current line selection.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-08-GIF-moving-blocks-code.gif)
```

2020-09-25 13:43 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 9:** *Adding cursors to multiple instances of the same selection.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-09-adding-cursors.png)
```suggestion
![**Image 9:** *Adding cursors to multiple instances of the same selection.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-09-GIF-adding-cursors.gif)
```

2020-09-25 13:43 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 10:** *Adding cursors to multiple lines.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-10-consecutive-cursors.png)
```suggestion
![**Image 10:** *Adding cursors to multiple lines.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-10-GIF-consecutive-cursors.gif)
```

2020-09-25 13:43 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 11:** *Peeking the definition.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-11-peek-definition.png)
```suggestion
![**Image 11:** *Peeking the definition.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-11-GIF-peek-definition.gif)
```

2020-09-25 13:44 UTC, eugenedorfling commented on tutorials/10-productivity-hacks.md
> +![**Image 12:** *Opening existing files.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-12-open-files.png)
```suggestion
![**Image 12:** *Opening existing files.*](https://i.ritzastatic.com/repl/codewithrepl/10-productivity/10-12-GIF-open-files.gif)
```

2020-09-30 08:14 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> -                    ball.speed = [0,-1]
Fixing this error by replacing the two ball.speed lines with ball.speed[0,-1]

2020-09-30 08:17 UTC, eugenedorfling commented on tutorials/07-building-a-game-with-pygame.md
> +                    ball.speed[1] = -2
```suggestion
                    ball.speed = [0,-1]
```

2020-10-28 10:25 UTC, sixhobbits requested changes

2020-10-28 10:25 UTC, sixhobbits commented on tutorials/00-overview.md
> +By this stage you'll have made a few mistakes. Learn the TDD way and how to write code that tests your other code to catch frustrating errors before they can hurt anyone. Repetitive jobs is what comp
```suggestion
By this stage you'll have made a few mistakes. Learn the TDD way and how to write code that tests your other code to catch frustrating errors before they can hurt anyone. Repetitive jobs are what computers do best after all.
```

2020-12-14 10:50 UTC, closed without merging